# Используем официальный Python-образ
FROM python:3.11-slim

# Устанавливаем ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt


# Копируем код
COPY . .

# Запускаем бота
CMD ["python", "Bot.py"]
